[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://interested-shirl-jonaswhite-1cd398c7.koyeb.app/api/:splat"
  status = 200
